apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
  project: project2
  purpose: multi-container-demo
spec: 
  container:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9 
    command: ["sleep", "1000"]  # this i used to run the container contineously without stopping