apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: projectk
    components: mysql
    tier: backend
    environment: dev
  spec: 
    containers:
    - name: nginx
      image: nginx