apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: projectk
    components: mysql
    tier: backend
    environment: dev
  annotations:
    descriptions: "This  pod is created to demonstrate pod annotations"
    jenkins: "https://jenkins.com/build/job/project1-catalogue/3"
  spec: 
    containers:
    - name: nginx
      image: nginx