apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
    components: mysql
    tier: backend
    environment: dev
  spec: 
    containers:
    - name: nginx
      image: nginx
      env:
      - name: COURSE
        value: "KUBERNETES"
      - name: LEARNER
        value: "ANAND J"