apiVersion: v1
kind: secret
metadata:
  name: pod-secret
  labels: 
    purpose: secret
    env: dev
type: opaque
data:
  username: "****" # give encoded username
  password: "****" # give encoded pass